language: php
sudo: required
php:
    - 7.4

cache:
    apt: true
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - composer test

notifications:
    email: false
